### ISSUE TITLE
Feature: UserFlow/Clickstream with session profiles

### ISSUE THREAD

**Issue by noone-silent** [Swetrix/swetrix-api#203]
The user flow feature is nice, for a general overview of site usage. It is especially useful for websites for apps not so much.
User flow also have disadvantages when a lot of url exists or data/time has been collected. For example look at the swetrix userflow of the last 12 months

![grafik](https://github.com/Swetrix/swetrix-api/assets/1089817/9141aa52-8fb7-4692-894a-1a280ccc4549)

Unreadable and completely useless.

For apps the interaction flow really needs to be attached to a session (doesn't need to be personal identified), to follow how the interaction with the website/app happened. To really identify bottlenecks in the navigation or click depth, surf logic.

OpenWebAnalytics has such session profiles and enables click stream tracking. It requires cookies and is multi session based, which is not needed most of the time.

![grafik](https://github.com/Swetrix/swetrix-api/assets/1089817/aadb7ece-afe6-407c-9c41-0842cc46f587)

Here I can click on any session profile and see what click journey / frontend experience this session had.

**Why is this such an important feature?**

For example, your app has a feature that allows to delete your account. You track this event via custom event or utm. Every week/month you look up this event/utm and want to know, why your users decided to delete their accounts. How can this be solved with swetrix? It's not possible. We have nice charts of pages, visits, entry and exit pages etc. but all this I can also get with [webalizer](https://webalizer.net/) or [goaccess](https://rt.goaccess.io/?20231101083340) without even installing a single line of tracking code, managing possible ad/script blocks and such. It's just a bunch of collected data to make nice charts, but it is not useful to improve anything.

Another example:
You have a funnel, but the funnel is not getting any attention or fails to convert. How to solve this problem with swetrix? You can't, because you can't see why this specific session lost the path or did not find the path at all. With a session profile you could identify the pages and SEE why this session has possible lost the path/interest or what ever. You also could use the pages to lead other customers correctly to your preferred goal.

**How can this be implemented?**
- Create an anonymous session profile on first visit
- This profile is only session based and doesn't need to be over multiple sessions
- Attach every page as click stream to this profile
- Create a profiles or click stream tab on the dashboard
- Show details about the session, that is usually on the dashboard (os, browser, country etc.) and also the click stream

**About privacy**

Again, this feature doesn't need any personal data and is only to identify user journeys/interaction problems and how to solve them. It doesn't need any multi session tracking at all.

**Final thoughts**

I'm absolutely sure, this can be solved in a privacy friendly way and is an absolutely killer feature for everyone that needs to know more about a browser/app session, then what pages have been visited. No other of this privacy focused analytics has this feature and to be honest are mostly useless bunch of charts, that rely on JS Code and a tracking friendly environment.

I tried swetrix because of the user flow feature, but like stated above, it is not useful most of the time.

**Why don't you use feature X then?**
- goAccess: Has everything swetrix has for websites and just rely on log files, that any web server has anyway. But it lacks tracking of a journey and isn't usable in an app.
- OWA: It's bloated, has low maintenance and code is mostly sync instead of async
- plausible, umami etc.: Same. Just some nice graphics about stats, but nothing useful to improve anything for the user/customer

Please do not take anything of this personal, it is just honest feedback and I try to improve things.

**Comment by Blaumaus** [comment]
Hi @noone-silent, thanks for the detailed feedback!

I agree that the user flow is something that should be fixed and we will be working on it soon. My thoughts were to add filters to the user flow so that users could select some pages and only see the flow between those pages, which would make it much cleaner and easier to navigate.

As for the clickstream feature - it sounds really cool and is something that should not be too difficult for Swetrix to implement.
I've created a ticket for this suggestion (https://github.com/Swetrix/roadmap/issues/178) and we'll be working on adding this to Swetrix soon.

I'll update you in this thread when this feature is done.

**Comment by Blaumaus** [comment]
Hello again, just wanted to let you know that I started working on that task and currently implementing an API for that (https://github.com/Swetrix/swetrix-api/pull/207).
You can expect the Clickstream feature to be added later this month or in early 2024.

**Comment by noone-silent** [comment]
Great news. Thank you. I will give it a try as soon as it is released

**Comment by Blaumaus** [comment]
The Clickstream feature will be released in the upcoming days after I finish testing and documenting it.
Here's how it will approximately look on the release day:

**Sessions list**
<img width="1440" alt="Screenshot 2023-12-20 at 19 52 15" src="https://github.com/Swetrix/swetrix-api/assets/35810911/de5f4f46-cf14-494a-9e70-b058d801618d">

**Session inspector**
<img width="1253" alt="Screenshot 2023-12-20 at 19 55 03" src="https://github.com/Swetrix/swetrix-api/assets/35810911/66a81139-bfa5-4f57-8c8b-dcc6111323b4">

Let me know if you think something could be improved or updated here

**Comment by Blaumaus** [comment]
Closing this issue as the Clickstream feature is now released 🎉

**Comment by noone-silent** [comment]
> Closing this issue as the Clickstream feature is now released 🎉

When will the new docker images be build?
